"""add votos table

Revision ID: 301ed943ed35
Revises: adbc43fc77b9
Create Date: 2025-11-16 21:23:35.422852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301ed943ed35'
down_revision: Union[str, Sequence[str], None] = 'adbc43fc77b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp_id', sa.Integer(), nullable=False),
    sa.Column('votacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('voto', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['votacion_id'], ['votaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votos_id'), 'votos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votos_id'), table_name='votos')
    op.drop_table('votos')
    # ### end Alembic commands ###
