"""Initial DB

Revision ID: 33c1c9fbc698
Revises: 
Create Date: 2025-11-04 13:03:17.012409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33c1c9fbc698'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poderes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('otorgante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('apoderado_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_otorgado', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_expiracion', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['apoderado_id'], ['propietarios.id'], name=op.f('poderes_apoderado_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['otorgante_id'], ['propietarios.id'], name=op.f('poderes_otorgante_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('poderes_pkey'))
    )
    op.create_index(op.f('ix_poderes_id'), 'poderes', ['id'], unique=False)
    op.create_table('asambleas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('asambleas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lugar', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='asambleas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_asambleas_id'), 'asambleas', ['id'], unique=False)
    op.create_table('comunicaciones_cobro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('propietario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deuda_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medio', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('recibido', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('autorizado_contacto', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deuda_id'], ['deudas.id'], name=op.f('comunicaciones_cobro_deuda_id_fkey')),
    sa.ForeignKeyConstraint(['propietario_id'], ['propietarios.id'], name=op.f('comunicaciones_cobro_propietario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comunicaciones_cobro_pkey'))
    )
    op.create_index(op.f('ix_comunicaciones_cobro_id'), 'comunicaciones_cobro', ['id'], unique=False)
    op.create_table('votaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asamblea_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('propuesta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('votos_favor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('votos_contra', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abstenciones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asamblea_id'], ['asambleas.id'], name=op.f('votaciones_asamblea_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('votaciones_pkey'))
    )
    op.create_index(op.f('ix_votaciones_id'), 'votaciones', ['id'], unique=False)
    op.create_table('poderes_votaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('propietario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('quorum_requerido', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_votacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('acta_guardada', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['propietario_id'], ['propietarios.id'], name=op.f('poderes_votaciones_propietario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('poderes_votaciones_pkey'))
    )
    op.create_index(op.f('ix_poderes_votaciones_id'), 'poderes_votaciones', ['id'], unique=False)
    op.create_table('deudas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('propietario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('valor_original', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('interes_mora', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_pago', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pagado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['propietario_id'], ['propietarios.id'], name=op.f('deudas_propietario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deudas_pkey'))
    )
    op.create_index(op.f('ix_deudas_id'), 'deudas', ['id'], unique=False)
    op.create_table('propietarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('propiedadID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('autorizacion_datos', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_autorizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('propietarios_pkey'))
    )
    op.create_index(op.f('ix_propietarios_id'), 'propietarios', ['id'], unique=False)
    op.create_index(op.f('ix_propietarios_correo'), 'propietarios', ['correo'], unique=False)
    # ### end Alembic commands ###
