"""CAMBIOS EN MODELOS

Revision ID: 3a13ceb8ce0a
Revises: 
Create Date: 2025-11-17 00:13:05.958858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a13ceb8ce0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos_juridicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp_id', sa.Integer(), nullable=False),
    sa.Column('deuda_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('abogado', sa.String(length=150), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deuda_id'], ['deudas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_juridicos_id'), 'casos_juridicos', ['id'], unique=False)
    op.create_table('historial_juridico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos_juridicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_juridico_id'), 'historial_juridico', ['id'], unique=False)
    op.drop_index(op.f('ix_votos_id'), table_name='votos')
    op.drop_table('votos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('votacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voto', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['votacion_id'], ['votaciones.id'], name=op.f('votos_votacion_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('votos_pkey'))
    )
    op.create_index(op.f('ix_votos_id'), 'votos', ['id'], unique=False)
    op.drop_index(op.f('ix_historial_juridico_id'), table_name='historial_juridico')
    op.drop_table('historial_juridico')
    op.drop_index(op.f('ix_casos_juridicos_id'), table_name='casos_juridicos')
    op.drop_table('casos_juridicos')
    # ### end Alembic commands ###
