"""QUITAR COMUNICACIONES

Revision ID: adbc43fc77b9
Revises: db540f1b4270
Create Date: 2025-11-16 21:08:15.105812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adbc43fc77b9'
down_revision: Union[str, Sequence[str], None] = 'db540f1b4270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comunicaciones_cobro_id'), table_name='comunicaciones_cobro')
    op.drop_table('comunicaciones_cobro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicaciones_cobro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('propietario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deuda_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medio', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('recibido', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('autorizado_contacto', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deuda_id'], ['deudas.id'], name=op.f('comunicaciones_cobro_deuda_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comunicaciones_cobro_pkey'))
    )
    op.create_index(op.f('ix_comunicaciones_cobro_id'), 'comunicaciones_cobro', ['id'], unique=False)
    # ### end Alembic commands ###
