"""Modelos Iniciales

Revision ID: b21aa21b432f
Revises: 0b04ca81e25f
Create Date: 2025-11-19 05:10:15.907582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21aa21b432f'
down_revision: Union[str, Sequence[str], None] = '0b04ca81e25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asambleas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('lugar', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asambleas_id'), 'asambleas', ['id'], unique=False)
    op.create_table('deudas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp_id', sa.Integer(), nullable=False),
    sa.Column('propietario_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('valor_original', sa.Float(), nullable=False),
    sa.Column('interes_mora', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deudas_id'), 'deudas', ['id'], unique=False)
    op.create_table('poderes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp_id', sa.Integer(), nullable=False),
    sa.Column('otorgante_id', sa.Integer(), nullable=False),
    sa.Column('apoderado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_otorgado', sa.Date(), nullable=False),
    sa.Column('fecha_expiracion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poderes_id'), 'poderes', ['id'], unique=False)
    op.create_table('casos_juridicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp_id', sa.Integer(), nullable=False),
    sa.Column('deuda_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('abogado', sa.String(length=150), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deuda_id'], ['deudas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_juridicos_id'), 'casos_juridicos', ['id'], unique=False)
    op.create_table('votaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hp_id', sa.Integer(), nullable=False),
    sa.Column('asamblea_id', sa.Integer(), nullable=False),
    sa.Column('propuesta', sa.Text(), nullable=False),
    sa.Column('votos_favor', sa.Integer(), nullable=True),
    sa.Column('votos_contra', sa.Integer(), nullable=True),
    sa.Column('abstenciones', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asamblea_id'], ['asambleas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votaciones_id'), 'votaciones', ['id'], unique=False)
    op.create_table('historial_juridico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos_juridicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_juridico_id'), 'historial_juridico', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_juridico_id'), table_name='historial_juridico')
    op.drop_table('historial_juridico')
    op.drop_index(op.f('ix_votaciones_id'), table_name='votaciones')
    op.drop_table('votaciones')
    op.drop_index(op.f('ix_casos_juridicos_id'), table_name='casos_juridicos')
    op.drop_table('casos_juridicos')
    op.drop_index(op.f('ix_poderes_id'), table_name='poderes')
    op.drop_table('poderes')
    op.drop_index(op.f('ix_deudas_id'), table_name='deudas')
    op.drop_table('deudas')
    op.drop_index(op.f('ix_asambleas_id'), table_name='asambleas')
    op.drop_table('asambleas')
    # ### end Alembic commands ###
