"""init

Revision ID: b5c1381cb84f
Revises: 
Create Date: 2025-11-16 20:46:39.309753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c1381cb84f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asambleas', sa.Column('hp_id', sa.Integer(), nullable=False))
    op.add_column('comunicaciones_cobro', sa.Column('hp_id', sa.Integer(), nullable=False))
    op.add_column('poderes', sa.Column('hp_id', sa.Integer(), nullable=False))
    op.add_column('votaciones', sa.Column('hp_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votaciones', 'hp_id')
    op.drop_column('poderes', 'hp_id')
    op.drop_column('comunicaciones_cobro', 'hp_id')
    op.drop_column('asambleas', 'hp_id')
    # ### end Alembic commands ###
